# Generated by Django 6.0.4 on 2026-04-30 15:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Movie title')),
                ('genre', models.CharField(max_length=100, verbose_name='Genre')),
                ('year', models.PositiveIntegerField(verbose_name='Release year')),
                ('status', models.CharField(choices=[('want', 'Want to watch'), ('watching', 'Watching'), ('watched', 'Watched')], default='want', max_length=20, verbose_name='Status')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Personal rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date added')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-created_at'],
            },
        ),
    ]
