# Generated by Django 6.0.4 on 2026-05-05 07:31

import stdstack.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdstack', '0003_rebuild_legacy_article_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(blank=True, storage=stdstack.storage.CloudinaryFallbackStorage(), upload_to='avatars/', verbose_name='Avatar'),
        ),
    ]
